export { BioPageOneBack } from "./bio/BioPageOneBack";
export { BioPageOneFront } from "./bio/BioPageOneFront";
export { BioPageThreeBack } from "./bio/BioPageThreeBack";
export { BioPageThreeFront } from "./bio/BioPageThreeFront";
export { BioPageTwoBack } from "./bio/BioPageTwoBack";
export { BioPageTwoFront } from "./bio/BioPageTwoFront";
export { CiklumsPage } from "./companies/CiklumsPage";
export { ElinextsPage } from "./companies/ElinextsPage";
export { ISolutionsPage } from "./companies/ISolutionsPage";
export { SDVsPage } from "./companies/SDVsPage";
export { BackCover } from "./covers/BackCover";
export { FrontCover } from "./covers/FrontCover";
export { DedicationPage } from "./DedicationPage";
export { LanguagesPage } from "./LanguagesPage";
export { SkillsPage } from "./SkillsPage";
export * from "./types";
